### ISSUE TITLE
Error when precompiling with Julia 1.11.0-rc2

### ISSUE THREAD

**Issue by PatrickHaecker** [JuliaGPU/GPUCompiler.jl#610]
I am not sure where this bug belongs to, but as I get the same error during precompilation both for `AllocCheck.jl` and for `oneAPI.jl` and both fail within `GPUCompiler`'s `__init__()` method with Julia 1.11.0-rc2 I am reporting it here:

```
Failed to precompile AllocCheck [9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a] to "~/.julia/compiled/v1.11/AllocCheck/jl_1EQw5R".
ERROR: LoadError: InitError: type Nothing has no field major
Stacktrace:
  [1] getproperty
    @ ./Base.jl:49 [inlined]
  [2] __init__()
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kqxyC/src/GPUCompiler.jl:64
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1263
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1251
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing)
    @ Base ./loading.jl:1195
  [6] _include_from_serialized
    @ ./loading.jl:1152 [inlined]
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128, stalecheck::Bool; reasons::Dict{String, Int64}, DEPOT_PATH::Vector{String})
    @ Base ./loading.jl:1917
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2378
  [9] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2243
 [10] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
 [11] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2230
 [13] macro expansion
    @ ./loading.jl:2169 [inlined]
 [14] macro expansion
    @ ./lock.jl:273 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2126
 [16] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
 [17] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
 [18] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2119
 [19] include
    @ ./Base.jl:558 [inlined]
 [20] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2749
 [21] top-level scope
    @ stdin:4
during initialization of module GPUCompiler
```

```
Failed to precompile oneAPI [8f75cd03-7ff8-4ecb-9b8f-daf728133b1b] to "/home/hp74lr/.julia/compiled/v1.11/oneAPI/jl_ugEhb4".
ERROR: LoadError: InitError: type Nothing has no field major
Stacktrace:
  [1] getproperty
    @ ./Base.jl:49 [inlined]
  [2] __init__()
    @ GPUCompiler ~/.julia/packages/GPUCompiler/kqxyC/src/GPUCompiler.jl:64
  [3] run_module_init(mod::Module, i::Int64)
    @ Base ./loading.jl:1263
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1251
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing)
    @ Base ./loading.jl:1195
  [6] _include_from_serialized
    @ ./loading.jl:1152 [inlined]
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128, stalecheck::Bool; reasons::Dict{String, Int64}, DEPOT_PATH::Vector{String})
    @ Base ./loading.jl:1917
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2378
  [9] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2243
 [10] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
 [11] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2230
 [13] macro expansion
    @ ./loading.jl:2169 [inlined]
 [14] macro expansion
    @ ./lock.jl:273 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2126
 [16] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
 [17] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
 [18] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2119
 [19] include
    @ ./Base.jl:558 [inlined]
 [20] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2749
 [21] top-level scope
    @ stdin:4
during initialization of module GPUCompiler
```

**Comment by maleadt** [comment]
You are using an outdated version of GPUCompiler; this has been fixed in the latest version.

**Comment by PatrickHaecker** [comment]
Thanks for the hint. Unfortunately, I could only update GPUCompiler after removing `oneApi.jl` and `AllocCheck.jl`. Not a very satisfying solution.

**Comment by maleadt** [comment]
The latest version of oneAPI.jl supports the latest version of GPUCompiler. In these situations, it can help to leave oneAPI.jl installed and force-install the latest version of GPUCompiler (`]add GPUCompiler@0.26.7`), which should reveal the actual conflict.

**Comment by PatrickHaecker** [comment]
Thanks a lot for the support! However, I still fail to get them working:

```
(@v1.11) pkg> add GPUCompiler@0.26.7
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package LLVM [929cbde3]:
 LLVM [929cbde3] log:
 ├─possible versions are: 0.9.0 - 8.0.0 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 4.0.0 - 8.0.0 or uninstalled
 ├─restricted by compatibility requirements with GPUCompiler [61eb1bfa] to versions: 8.0.0
 │ └─GPUCompiler [61eb1bfa] log:
 │   ├─possible versions are: 0.1.0 - 0.26.7 or uninstalled
 │   └─restricted to versions 0.26.7 by an explicit requirement, leaving only versions: 0.26.7
 └─restricted by compatibility requirements with oneAPI [8f75cd03] to versions: 6.0.0 - 7.2.1 — no versions left
   └─oneAPI [8f75cd03] log:
     ├─possible versions are: 0.1.0 - 1.5.0 or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0 - 1.5.0
     └─restricted by compatibility requirements with GPUCompiler [61eb1bfa] to versions: 1.5.0 or uninstalled, leaving only versions: 1.5.0
       └─GPUCompiler [61eb1bfa] log: see above
```

```
(@v1.11) pkg> add LLVM.jl@8.0.0
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package oneAPI [8f75cd03]:
 oneAPI [8f75cd03] log:
 ├─possible versions are: 0.1.0 - 1.5.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0 - 1.5.0
 └─restricted by compatibility requirements with LLVM [929cbde3] to versions: uninstalled — no versions left
   └─LLVM [929cbde3] log:
     ├─possible versions are: 0.9.0 - 8.0.0 or uninstalled
     └─restricted to versions 8.0.0 by an explicit requirement, leaving only versions: 8.0.0
```

**Comment by maleadt** [comment]
This is expected to fail, but at least it shows the problem: oneAPI.jl isn't compatible with LLVM 8 yet. I'll tag a new version with support for that version of LLVM.jl. I suggest you request the same on the AllocCheck.jl repository.

**Comment by PatrickHaecker** [comment]
[Request done](https://github.com/JuliaLang/AllocCheck.jl/issues/79)
